//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EkzDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int NumberOrder { get; set; }
        public int IdBook { get; set; }
        public int Count { get; set; }
        public System.DateTime DateOrder { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
